name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and test using Docker
        run: .docker/build.sh

      - name: End-to-end test of Docker image
        run: .docker/test.sh

      - name: Extract build results from docker image
        uses: shrink/actions-docker-extract@v3
        with:
          image: "oso:builder"
          path: "app/target"
          destination: "."

      - name: List files
        run: ls -la ./target

      - name: Generate code coverage report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          minimum_coverage: 80
          fail_below_threshold: true
          publish_only_summary: true
          skip_check_run: true

      - name: Add code coverage report to workflow run summary
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./target/reports
          retention-days: 7

      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./target/site
          retention-days: 7

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: ./target/*.jar
          retention-days: 7